### ISSUE TITLE
Button 7 not working

### ISSUE THREAD

**Issue by GreenSnakeLinux** [canrollas/Remote-Controller#3]
Hello
Great work
I have found an issue on button: '7'
you have put txt instead of seven:

```
  def seven(self):
      return self.send_key_command(self.kumanda_keycode.txt)
```

Also, do you know the keycode for 'Rewind' ? It's missing in class kumanda_keycode

thanks

**Comment by canrollas** [comment]
Thanks for your warning I will fix it now. 
This is Keys I think you are looking for
play= "-2548:-4015"
        pause= "-2480:-4086"
        stop= "-2545:-4014"
        prev= "-2538:-4005"
        forward= "-2555:-4023"
        nextt="-2546:4004"

**Comment by GreenSnakeLinux** [comment]
no, I'm looking for the backward/rewind button
You've got Previous and Next. You've got Forward but not the opposite.
Maybe we can guess it, can you try: -2556:-4022 or -2554:-4024 ?
I don't own the TV for test that. Thanks

**Comment by canrollas** [comment]
Yes , It worked thanks !
